### ISSUE TITLE
arrow position

### ISSUE THREAD

**Issue by Zwei8** [henus/jquery-gauge#3]
Hi, please fix arrow position in Firefox.
When I use Chrome is not problem, but when use Firefox, the arrow not in position.

I'm using Firefox 47

![image](https://cloud.githubusercontent.com/assets/4384394/17128601/24ff2124-5338-11e6-949e-8779951462ad.png)

**Comment by nenadelite** [comment]
I have the same issue on Firefox.

**Comment by nenadelite** [comment]
Resolve it! 

It's in jquery-gauge.css class .b-gauge__arrow.

Need to be 

{transform-origin: 50% 50%; -webkit-transform-origin: 50% 100%; -moz-transform-origin: 50% 50%;}

**Comment by NormTheThird** [comment]
That did not work for me in Firefox.  Is there going to be a fix for this?  Im using Firefox 49.0.1

**Comment by henus** [comment]
Cross-browser fix for SVG transform-origin arrow position (transform-origin from css moved to native SVG transform attribute) https://github.com/henus/jquery-gauge/commit/5178f916c4cf6daaa643bab7e4c838526217cd17

**Comment by NormTheThird** [comment]
Thanks
